version: "3"

networks:
  wedding-network:
    driver: bridge
  loki:
    driver: bridge

services:
  loki:
    container_name: loki
    image: grafana/loki:2.8.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    container_name: promtail
    image: grafana/promtail:2.8.0
    volumes:
      - ./config/promtail:/etc/promtail
      - ./log:/var/log/application
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    container_name: grafana
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki

  backend:
    container_name: wedding-backend
    image: backend
    build:
      context: .
      dockerfile: Dockerfile-local
    ports:
      - "8081:8081"
    volumes:
      - ./log:/app/log
    networks:
      - loki
      - wedding-network
    depends_on:
      - mysql

  mysql:
    container_name: wedding-mysql
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Seoul
      LC_ALL: C.UTF-8
    env_file:
      - .env
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    networks:
      - wedding-network

