server:
  port: ${{ secrets.SERVER_PORT }}

#cloud:
#  aws:
#    credentials:
#      access-key: ${{ secrets.AWS_ACCESS_KEY }}
#      secret-key: ${{ secrets.AWS_SECRET_KEY }}
#    s3:
#      url: ${{ secrets.AWS_S3_URL }}
#    region:
#      static: ${{ secrets.AWS_REGION }}
#    stack:
#      auto: false

spring:
  datasource:
    url: ${{ secrets.DATABASE_URL }}
    username: ${{ secrets.DATABASE_USERNAME }}
    password: ${{ secrets.DATABASE_PASSWORD }}
    driver-class-name: ${{ secrets.DATABASE_DRIVER }}

  jpa:
    database: ${{ secrets.DATABASE_DRIVER }}
    database-platform: ${{ secrets.DATABASE_DRIVER }}
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

jwt:
  secret:
    key: ${{ secrets.JWT_SECRET }}
    access-valid-time: ${{ secrets.JWT_ACCESS_TIME }}
    refresh-valid-time: ${{ secrets.JWT_REFRESH_TIME }}

decorator:
  datasource:
    p6spy:
      enable-logging: false

logging:
  level:
    org.hibernate: error
