# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches:
    - feature/WEDPRO-62


permissions:
  contents: read

jobs:
#  test:
#    runs-on: ubuntu-latest
#
#    services:
#      mysql:
#        image: mysql
#        env:
#          MYSQL_DATABASE: wedding_registry_test
#          MYSQL_ROOT_PASSWORD: password
#        ports:
#          - 3306:3306
#        options: >-
#          --health-cmd="mysqladmin ping"
#          --health-interval=10s
#          --health-timeout=5s
#          --health-retries=3
#
#    steps:
#    - uses: actions/checkout@v3.5.2
#    - name: Set up JDK 11
#      uses: actions/setup-java@v3.11.0
#      with:
#        distribution: 'zulu'
#        java-version: '11'
#    - name: Do Unit Test
#      run: ./gradlew :test
        
        

  build:
#    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.4.2
      
    - name: Execute Gradle build
      run: ./gradlew bootJar















